import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { validateStaticSkillContract } from "./acceptance/validate-static-contract.mjs";
import { validateEvidence } from "./acceptance/validate-codex-smoke.mjs";
import { decisionBank, resolveDecisionId } from "./acceptance/codex-smoke-scenario.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), ".."); const e = resolve(root, "tests/acceptance/evidence");
const [skill, scenarioText, manifestText, derivedBytes] = await Promise.all([readFile(resolve(root,"skills/meta-prompt/SKILL.md"),"utf8"),readFile(resolve(root,"tests/acceptance/happy-path.json"),"utf8"),readFile(resolve(e,"manifest.json"),"utf8"),readFile(resolve(e,"derived-transcript.json"))]);
const manifest=JSON.parse(manifestText), transcript=JSON.parse(derivedBytes), rawFiles=await Promise.all(manifest.entries.map((x)=>readFile(resolve(e,"raw",x.raw))));
assert.equal(validateStaticSkillContract({skill,scenario:JSON.parse(scenarioText)}).status,"PASS");
assert.equal(resolveDecisionId("target"), "target", "registered ID preserved");
assert.equal(resolveDecisionId("data-directory"), "data-directory", "material data-directory decision registered");
assert.throws(() => resolveDecisionId("unreviewed_alias"), /unknown or resolved Decision ID unreviewed_alias/);
assert.throws(() => resolveDecisionId("target", decisionBank, ["target"]), /unknown or resolved Decision ID target/);
assert.equal(validateEvidence({transcript,manifest,rawFiles,derivedBytes}).status,"PASS");
const hash=(v)=>createHash("sha256").update(v).digest("hex");
const rejected=(name, change, expected)=>{const c={transcript:structuredClone(transcript),manifest:structuredClone(manifest),rawFiles:[...rawFiles]};change(c);c.derivedBytes=Buffer.from(`${JSON.stringify(c.transcript,null,2)}\n`);c.manifest.derivedSha256=hash(c.derivedBytes);assert.throws(()=>validateEvidence(c),expected,name);};
rejected("false valid provenance",c=>{c.manifest.supportedModel="gpt-fabricated";c.manifest.captureUtc="2099-01-01T00:00:00.000Z";c.manifest.hostVersion="codex-cli 999.999.999";c.manifest.threadId="11111111-1111-4111-8111-111111111111";},/false model provenance/);
rejected("rewritten user command",c=>{c.manifest.entries[1].args[c.manifest.entries[1].args.length-1]="Actually implement a cloud GUI now";c.transcript.turns[1].user="Actually implement a cloud GUI now";},/manifest command shape|derived binding/);
rejected("pre signal analysis",c=>{c.transcript.turns[1].assistant="I will analyze and solve this now.";},/derived binding/);
rejected("sixth two decision",c=>{c.transcript.turns[9].assistant="Recommended choice? Another choice?";},/derived binding/);
rejected("false quality delivery",c=>{c.transcript.turns.at(-1).assistant="**English Final Prompt**\nBuild a cloud GUI\n**Review Translation**\n번역\n**Run Instructions**\nFresh Run only the English Final Prompt. Quality Gate: Passed";},/derived binding/);
console.log("meta-prompt canonical contract: PASS");
